---
title: "World Games 2025 Ultimate Fantasy Value Graph"
---



```{r include=FALSE}
library(rio)
library(tidyverse)
library(janitor)
library(here)
library(ggplot2)
library(plotly)

```

```{r echo=FALSE, message=FALSE, warning=FALSE}
player_reference <- import(here("ALL TEAMS ALL DRAFTS World Games 2025 Fantasy League Tracker - Player List.csv")) %>% 
  rename(TeamName=`Name+Team`) %>% 
  mutate(text = paste(
    First,Last, Team,
    "\nGoals :",Goals,
    "\nAssists :",Assists,
    "\nBlocks :",Block,
    "\nThrowing Yards :",ThrowYds,
    "\nReceiving Yards :",RecYds,
    "\nTurns :",Turn))


draft_reference <- import(here("ALL TEAMS ALL DRAFTS World Games 2025 Fantasy League Tracker - Copy of Player List.csv"))

player_picks <- draft_reference %>% 
  group_by(TeamName) %>% 
  filter(Owner!="") %>% 
  summarise(times_picked = n())




player_reference<-left_join(player_reference,player_picks) 

player_reference$times_picked<- replace_na(player_reference$times_picked,0) 

player_reference<- player_reference %>% 
  mutate(times_not_picked = 10-times_picked)
  
?ggplot
pick_efficiency_graph<-player_reference %>% 
  ggplot(aes(x=times_picked,y=FantasyPts,text=text,colour=Team,shape=GM)) +
  geom_point(position="jitter",size=3)+
  labs(title = "2025 WG Ultimate Fantasy Performance",
       subtitle = "Triangles are MMP, Circles are WMP")+
  theme_minimal()


ggplotly(pick_efficiency_graph,tooltip="text") %>% 
  toWebGL()


```

